name: 'AI Triage Assistant'
description: 'An AI assistant that triages issues by applying labels based on the issue content.'
author: 'mattleibow'

branding:
  icon: 'feather'
  color: 'blue'

inputs:
  issue:
    description: 'The issue number of the issue to triage'
    required: false
    default: ''

  # Label selection inputs
  template:
    description: 'Triage template to use: multi-label, single-label, regression, missing-info'
    required: false
    default: ''
  label:
    description: 'The specific label to use'
    required: false
    default: ''
  label-prefix:
    description: 'Prefix for label search (e.g., platform/, area-, etc.)'
    required: false
    default: ''

  # Label and comment posting inputs
  apply-labels:
    description: 'Whether to apply labels to the issue'
    required: false
    default: 'false'
  apply-comment:
    description: 'Whether to comment on the issue with the AI response'
    required: false
    default: 'false'
  comment-footer:
    description: 'Footer text to append to the AI response comment'
    required: false
    default: '_This entire triage process was automated by AI and mistakes may have been made. Please let us know so we can continue to improve._'

outputs:
  response-file:
    description: 'The file that contains the result of AI inference'
    value: ${{ steps.inference.outputs.response-file }}

runs:
  using: 'composite'
  steps:

    - name: Select labels
      id: select-labels
      if: ${{ inputs.template != '' }}
      uses: ${{ github.action_path }}/src/select-labels
      with:
        issue: ${{ inputs.issue }}
        template: ${{ inputs.template }}
        label: ${{ inputs.label }}
        label-prefix: ${{ inputs.label-prefix }}

    - name: Apply labels and comment
      id: apply
      if: ${{ inputs.apply-labels == 'true' || inputs.apply-comment == 'true' }}
      uses: ${{ github.action_path }}/src/apply
      with:
        issue: ${{ inputs.issue }}
        input-files: ${{ steps.select-labels.outputs.response-file }}
        footer: ${{ inputs.comment-footer }}
        apply-labels: ${{ inputs.apply-labels }}
        apply-comment: ${{ inputs.apply-comment }}