name: 'Apply Labels and Comment'
description: 'Summarize the triage, comment on the issue, and apply labels.'

inputs:
  issue:
    description: 'The issue number of the issue to triage'
    required: true
  input-files:
    description: 'Comma-separated or newline-separated list of JSON files with results to merge'
    required: false
  footer:
    description: 'Footer text to append to the AI response comment'
    required: false
    default: '_This entire triage process was automated by AI and mistakes may have been made. Please let us know so we can continue to improve._'
  apply-labels:
    description: 'Whether to apply labels to the issue'
    required: false
    default: 'false'
  apply-comment:
    description: 'Whether to comment on the issue with the AI response'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:

    - name: Merge response JSON files
      id: merge
      shell: pwsh
      run: |
        $out = "${{ runner.temp }}/triage-assistant/responses.json"
        ${{ github.action_path }}/merge-responses.ps1 `
          -InputFiles "${{ inputs.input-files }}" `
          -InputDir "${{ runner.temp }}/triage-assistant/responses" `
          -Output "$out"
        "responses-file=$out" >> $env:GITHUB_OUTPUT

    - name: Create System prompt file
      id: create-system-prompt
      uses: ./src/gen-prompt
      with:
        template: ${{ github.action_path }}/system-prompt.md
        output: ${{ runner.temp }}/triage-apply/prompts/system-prompt.md
        replacements: |
          ISSUE_NUMBER=${{ inputs.issue }}
          ISSUE_REPO=${{ github.repository }}
          MERGED_JSON=${{ steps.merge.outputs.responses-file }}

    - name: Create User prompt file
      id: create-user-prompt
      uses: ./src/gen-prompt
      with:
        template: ${{ github.action_path }}/user-prompt.md
        output: ${{ runner.temp }}/triage-apply/prompts/user-prompt.md
        replacements: |
          ISSUE_NUMBER=${{ inputs.issue }}
          ISSUE_REPO=${{ github.repository }}
          MERGED_JSON=${{ steps.merge.outputs.responses-file }}

    - name: Run AI inference
      id: inference
      uses: mattleibow/ai-inference@mattleibow/response-file
      with:
        system-prompt-file: "${{ steps.create-system-prompt.outputs.prompt }}"
        prompt-file: "${{ steps.create-user-prompt.outputs.prompt }}"
        response-file: "${{ runner.temp }}/triage-apply/responses/response.md"
        max-tokens: 500

    - name: Log the response file
      shell: pwsh
      run: |
        echo "Response file: ${{ steps.inference.outputs.response-file }}"
        cat "${{ steps.inference.outputs.response-file }}"

    - name: Comment on the issue with summary
      uses: actions/github-script@v7
      if: ${{ inputs.apply-comment == 'true' }}
      with:
        script: |
          const fs = require('fs');
          const summary = fs.readFileSync('${{ steps.inference.outputs.response }}', 'utf8');

          const issueNumber = parseInt('${{ inputs.issue }}', 10);
          const footer = '${{ inputs.footer }}';

          const commentBody = `${summary}\n\n${footer}`;
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            body: commentBody
          });

    - name: Apply labels to the issue
      uses: actions/github-script@v7
      if: ${{ inputs.apply-labels == 'true' }}
      with:
        script: |
          const fs = require('fs');
          const mergedJson = fs.readFileSync('${{ steps.merge.outputs.merged-file }}', 'utf8');
          const merged = JSON.parse(mergedJson);

          const issueNumber = parseInt('${{ inputs.issue }}', 10);

          const labels = merged.labels
            .map(l => l.label)
            .filter(Boolean);

          if (labels.length > 0) {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels
            });
          }
