name: 'Advanced Multi-Step Triage'

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write
  models: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Determine overlap labels
        uses: mattleibow/triage-assistant/apply-labels@v0.7.0
        with:
          label-prefix: 'overlap-'
          template: 'multi-label'

      - name: Determine area label
        uses: mattleibow/triage-assistant/apply-labels@v0.7.0
        with:
          label-prefix: 'area-'
          template: 'single-label'

      - name: Check for regression
        uses: mattleibow/triage-assistant/apply-labels@v0.7.0
        with:
          label: 'regression'
          template: 'regression'

      - name: Apply all labels and add comment
        uses: mattleibow/triage-assistant/apply-labels@v0.7.0
        with:
          apply-labels: true
          apply-comment: true
