name: 'Combined Triage and Engagement'

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write
  repository-projects: write
  models: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Apply AI-powered labels
      - name: Apply area labels
        uses: mattleibow/triage-assistant/apply-labels@v0.7.0
        with:
          template: multi-label
          label-prefix: 'area-'
          apply-labels: true
          apply-comment: true

      # Step 2: Calculate engagement score
      - name: Calculate engagement score
        uses: mattleibow/triage-assistant/engagement-score@v0.7.0
        with:
          issue: ${{ github.event.issue.number }}
          apply-scores: true
          project: 1 # Replace with your project number
          project-column: 'Engagement Score'
