name: 'Triage Generate Prompt'
description: 'Generates a prompt file from a template using provided labels and parameters.'

inputs:
  template:
    description: 'Path to the prompt template file'
    required: true
  output:
    description: 'Path to the output prompt file'
    required: true
  replacements:
    description: |
      Multiline mapping of placeholder names to values in the format:
      NAME1=value1
      NAME2=value2
      
      For example:
      LABEL=platform/android
      LABEL_PREFIX=area-
    required: false
    default: ''

outputs:
  prompt:
    description: 'The generated prompt file path'
    value: ${{ steps.create-prompt.outputs.prompt }}

runs:
  using: 'composite'
  steps:

    - name: Create prompt file
      id: create-prompt
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        ${{ github.action_path }}/process-prompt-template.ps1 `
          -Template "${{ inputs.template }}" `
          -Output "${{ inputs.output }}" `
          -Replacements "${{ inputs.replacements }}"
        "prompt=${{ inputs.output }}" >> $env:GITHUB_OUTPUT
