export function searchIssuesResults() {
  return [
    {
      id: '3265449488',
      owner: 'mattleibow',
      repo: 'triage-assistant',
      number: 33,
      assignees: [
        {
          login: 'mattleibow',
          type: 'User'
        }
      ],
      body: '## Description\n\nThis is another issue for the unit tests and not a real one.\n\nWe need some real data to allow for real tests.\n\nThis one has some more context though. We are wanting to relate this issue with the AI and prompt system.',
      closedAt: null,
      createdAt: new Date('2025-07-26T11:14:12.000Z'),
      updatedAt: new Date('2025-07-26T11:14:39.000Z'),
      state: 'open',
      title: 'An second issue for the unit tests',
      user: {
        login: 'mattleibow',
        type: 'User'
      }
    },
    {
      id: '3265422585',
      owner: 'mattleibow',
      repo: 'triage-assistant',
      number: 32,
      assignees: [
        {
          login: 'mattleibow',
          type: 'User'
        },
        {
          login: 'Copilot',
          type: 'Bot'
        }
      ],
      body: '## Description\n\nThis is an issue for the unit tests and not a real one.\n\nWe need some real data to allow for real tests.',
      closedAt: null,
      createdAt: new Date('2025-07-26T10:36:49.000Z'),
      updatedAt: new Date('2025-07-26T10:38:08.000Z'),
      state: 'open',
      title: 'An issue for the unit tests',
      user: {
        login: 'mattleibow',
        type: 'User'
      }
    },
    {
      id: '3263967334',
      owner: 'mattleibow',
      repo: 'triage-assistant',
      number: 31,
      assignees: [],
      body: 'Test',
      closedAt: new Date('2025-07-26T10:33:19.000Z'),
      createdAt: new Date('2025-07-25T17:53:45.000Z'),
      updatedAt: new Date('2025-07-26T10:33:19.000Z'),
      state: 'closed',
      title: 'Test Issue',
      user: {
        login: 'mattleibow',
        type: 'User'
      }
    }
  ]
}

export function githubRestSearchIssuesResponse() {
  return {
    status: 200,
    url: 'https://api.github.com/search/issues?q=is%3Aissue%20created%3A2025-07-25..2025-07-26%20repo%3Amattleibow%2Ftriage-assistant&sort=created&order=desc&per_page=100&advanced_search=true',
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers':
        'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'cache-control': 'no-cache',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 25 Aug 2025 10:09:50 GMT',
      'github-authentication-token-expiration': '2025-09-04 01:14:24 UTC',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'github.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept, Authorization, Cookie, X-GitHub-OTP,Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': '',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'D3C4:31C3EB:FE747:1C9FA5:68AC366E',
      'x-oauth-scopes': 'public_repo, read:project',
      'x-ratelimit-limit': '30',
      'x-ratelimit-remaining': '28',
      'x-ratelimit-reset': '1756116624',
      'x-ratelimit-resource': 'search',
      'x-ratelimit-used': '2',
      'x-xss-protection': '0'
    },
    data: {
      total_count: 3,
      incomplete_results: false,
      items: [
        {
          url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/33',
          repository_url: 'https://api.github.com/repos/mattleibow/triage-assistant',
          labels_url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/33/labels{/name}',
          comments_url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/33/comments',
          events_url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/33/events',
          html_url: 'https://github.com/mattleibow/triage-assistant/issues/33',
          id: 3265449488,
          node_id: 'I_kwDOOy552s7Cos4Q',
          number: 33,
          title: 'An second issue for the unit tests',
          user: {
            login: 'mattleibow',
            id: 1096616,
            node_id: 'MDQ6VXNlcjEwOTY2MTY=',
            avatar_url: 'https://avatars.githubusercontent.com/u/1096616?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/mattleibow',
            html_url: 'https://github.com/mattleibow',
            followers_url: 'https://api.github.com/users/mattleibow/followers',
            following_url: 'https://api.github.com/users/mattleibow/following{/other_user}',
            gists_url: 'https://api.github.com/users/mattleibow/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/mattleibow/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/mattleibow/subscriptions',
            organizations_url: 'https://api.github.com/users/mattleibow/orgs',
            repos_url: 'https://api.github.com/users/mattleibow/repos',
            events_url: 'https://api.github.com/users/mattleibow/events{/privacy}',
            received_events_url: 'https://api.github.com/users/mattleibow/received_events',
            type: 'User',
            user_view_type: 'public',
            site_admin: false
          },
          labels: [
            {
              id: 8698283066,
              node_id: 'LA_kwDOOy552s8AAAACBnVEOg',
              url: 'https://api.github.com/repos/mattleibow/triage-assistant/labels/wontfix',
              name: 'wontfix',
              color: 'ffffff',
              default: true,
              description: 'This will not be worked on'
            },
            {
              id: 8698386787,
              node_id: 'LA_kwDOOy552s8AAAACBnbZYw',
              url: 'https://api.github.com/repos/mattleibow/triage-assistant/labels/overlap-ai',
              name: 'overlap-ai',
              color: '1E7D91',
              default: false,
              description: 'Things that may be related to AI inference'
            },
            {
              id: 8698395702,
              node_id: 'LA_kwDOOy552s8AAAACBnb8Ng',
              url: 'https://api.github.com/repos/mattleibow/triage-assistant/labels/overlap-prompts',
              name: 'overlap-prompts',
              color: '1E7D91',
              default: false,
              description: 'Things relating to prompts'
            },
            {
              id: 9006652542,
              node_id: 'LA_kwDOOy552s8AAAACGNacfg',
              url: 'https://api.github.com/repos/mattleibow/triage-assistant/labels/area-testing',
              name: 'area-testing',
              color: '0075ca',
              default: false,
              description: 'Things relating to testing and the test suites'
            }
          ],
          state: 'open',
          locked: false,
          assignee: {
            login: 'mattleibow',
            id: 1096616,
            node_id: 'MDQ6VXNlcjEwOTY2MTY=',
            avatar_url: 'https://avatars.githubusercontent.com/u/1096616?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/mattleibow',
            html_url: 'https://github.com/mattleibow',
            followers_url: 'https://api.github.com/users/mattleibow/followers',
            following_url: 'https://api.github.com/users/mattleibow/following{/other_user}',
            gists_url: 'https://api.github.com/users/mattleibow/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/mattleibow/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/mattleibow/subscriptions',
            organizations_url: 'https://api.github.com/users/mattleibow/orgs',
            repos_url: 'https://api.github.com/users/mattleibow/repos',
            events_url: 'https://api.github.com/users/mattleibow/events{/privacy}',
            received_events_url: 'https://api.github.com/users/mattleibow/received_events',
            type: 'User',
            user_view_type: 'public',
            site_admin: false
          },
          assignees: [
            {
              login: 'mattleibow',
              id: 1096616,
              node_id: 'MDQ6VXNlcjEwOTY2MTY=',
              avatar_url: 'https://avatars.githubusercontent.com/u/1096616?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/mattleibow',
              html_url: 'https://github.com/mattleibow',
              followers_url: 'https://api.github.com/users/mattleibow/followers',
              following_url: 'https://api.github.com/users/mattleibow/following{/other_user}',
              gists_url: 'https://api.github.com/users/mattleibow/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/mattleibow/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/mattleibow/subscriptions',
              organizations_url: 'https://api.github.com/users/mattleibow/orgs',
              repos_url: 'https://api.github.com/users/mattleibow/repos',
              events_url: 'https://api.github.com/users/mattleibow/events{/privacy}',
              received_events_url: 'https://api.github.com/users/mattleibow/received_events',
              type: 'User',
              user_view_type: 'public',
              site_admin: false
            }
          ],
          milestone: {
            url: 'https://api.github.com/repos/mattleibow/triage-assistant/milestones/1',
            html_url: 'https://github.com/mattleibow/triage-assistant/milestone/1',
            labels_url: 'https://api.github.com/repos/mattleibow/triage-assistant/milestones/1/labels',
            id: 13352621,
            node_id: 'MI_kwDOOy552s4Ay76t',
            number: 1,
            title: 'v1',
            description: null,
            creator: {
              login: 'mattleibow',
              id: 1096616,
              node_id: 'MDQ6VXNlcjEwOTY2MTY=',
              avatar_url: 'https://avatars.githubusercontent.com/u/1096616?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/mattleibow',
              html_url: 'https://github.com/mattleibow',
              followers_url: 'https://api.github.com/users/mattleibow/followers',
              following_url: 'https://api.github.com/users/mattleibow/following{/other_user}',
              gists_url: 'https://api.github.com/users/mattleibow/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/mattleibow/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/mattleibow/subscriptions',
              organizations_url: 'https://api.github.com/users/mattleibow/orgs',
              repos_url: 'https://api.github.com/users/mattleibow/repos',
              events_url: 'https://api.github.com/users/mattleibow/events{/privacy}',
              received_events_url: 'https://api.github.com/users/mattleibow/received_events',
              type: 'User',
              user_view_type: 'public',
              site_admin: false
            },
            open_issues: 2,
            closed_issues: 0,
            state: 'open',
            created_at: '2025-07-26T10:37:16Z',
            updated_at: '2025-07-26T11:14:13Z',
            due_on: null,
            closed_at: null
          },
          comments: 1,
          created_at: '2025-07-26T11:14:12Z',
          updated_at: '2025-07-26T11:14:39Z',
          closed_at: null,
          author_association: 'OWNER',
          active_lock_reason: null,
          sub_issues_summary: {
            total: 0,
            completed: 0,
            percent_completed: 0
          },
          issue_dependencies_summary: {
            blocked_by: 0,
            total_blocked_by: 0,
            blocking: 0,
            total_blocking: 0
          },
          body: '## Description\n\nThis is another issue for the unit tests and not a real one.\n\nWe need some real data to allow for real tests.\n\nThis one has some more context though. We are wanting to relate this issue with the AI and prompt system.',
          reactions: {
            url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/33/reactions',
            total_count: 8,
            '+1': 1,
            '-1': 1,
            laugh: 1,
            hooray: 1,
            confused: 1,
            heart: 1,
            rocket: 1,
            eyes: 1
          },
          timeline_url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/33/timeline',
          performed_via_github_app: null,
          state_reason: null,
          score: 1
        },
        {
          url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/32',
          repository_url: 'https://api.github.com/repos/mattleibow/triage-assistant',
          labels_url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/32/labels{/name}',
          comments_url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/32/comments',
          events_url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/32/events',
          html_url: 'https://github.com/mattleibow/triage-assistant/issues/32',
          id: 3265422585,
          node_id: 'I_kwDOOy552s7ComT5',
          number: 32,
          title: 'An issue for the unit tests',
          user: {
            login: 'mattleibow',
            id: 1096616,
            node_id: 'MDQ6VXNlcjEwOTY2MTY=',
            avatar_url: 'https://avatars.githubusercontent.com/u/1096616?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/mattleibow',
            html_url: 'https://github.com/mattleibow',
            followers_url: 'https://api.github.com/users/mattleibow/followers',
            following_url: 'https://api.github.com/users/mattleibow/following{/other_user}',
            gists_url: 'https://api.github.com/users/mattleibow/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/mattleibow/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/mattleibow/subscriptions',
            organizations_url: 'https://api.github.com/users/mattleibow/orgs',
            repos_url: 'https://api.github.com/users/mattleibow/repos',
            events_url: 'https://api.github.com/users/mattleibow/events{/privacy}',
            received_events_url: 'https://api.github.com/users/mattleibow/received_events',
            type: 'User',
            user_view_type: 'public',
            site_admin: false
          },
          labels: [
            {
              id: 8698283066,
              node_id: 'LA_kwDOOy552s8AAAACBnVEOg',
              url: 'https://api.github.com/repos/mattleibow/triage-assistant/labels/wontfix',
              name: 'wontfix',
              color: 'ffffff',
              default: true,
              description: 'This will not be worked on'
            },
            {
              id: 9006652542,
              node_id: 'LA_kwDOOy552s8AAAACGNacfg',
              url: 'https://api.github.com/repos/mattleibow/triage-assistant/labels/area-testing',
              name: 'area-testing',
              color: '0075ca',
              default: false,
              description: 'Things relating to testing and the test suites'
            }
          ],
          state: 'open',
          locked: false,
          assignee: {
            login: 'mattleibow',
            id: 1096616,
            node_id: 'MDQ6VXNlcjEwOTY2MTY=',
            avatar_url: 'https://avatars.githubusercontent.com/u/1096616?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/mattleibow',
            html_url: 'https://github.com/mattleibow',
            followers_url: 'https://api.github.com/users/mattleibow/followers',
            following_url: 'https://api.github.com/users/mattleibow/following{/other_user}',
            gists_url: 'https://api.github.com/users/mattleibow/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/mattleibow/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/mattleibow/subscriptions',
            organizations_url: 'https://api.github.com/users/mattleibow/orgs',
            repos_url: 'https://api.github.com/users/mattleibow/repos',
            events_url: 'https://api.github.com/users/mattleibow/events{/privacy}',
            received_events_url: 'https://api.github.com/users/mattleibow/received_events',
            type: 'User',
            user_view_type: 'public',
            site_admin: false
          },
          assignees: [
            {
              login: 'mattleibow',
              id: 1096616,
              node_id: 'MDQ6VXNlcjEwOTY2MTY=',
              avatar_url: 'https://avatars.githubusercontent.com/u/1096616?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/mattleibow',
              html_url: 'https://github.com/mattleibow',
              followers_url: 'https://api.github.com/users/mattleibow/followers',
              following_url: 'https://api.github.com/users/mattleibow/following{/other_user}',
              gists_url: 'https://api.github.com/users/mattleibow/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/mattleibow/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/mattleibow/subscriptions',
              organizations_url: 'https://api.github.com/users/mattleibow/orgs',
              repos_url: 'https://api.github.com/users/mattleibow/repos',
              events_url: 'https://api.github.com/users/mattleibow/events{/privacy}',
              received_events_url: 'https://api.github.com/users/mattleibow/received_events',
              type: 'User',
              user_view_type: 'public',
              site_admin: false
            },
            {
              login: 'Copilot',
              id: 198982749,
              node_id: 'BOT_kgDOC9w8XQ',
              avatar_url: 'https://avatars.githubusercontent.com/in/1143301?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/Copilot',
              html_url: 'https://github.com/apps/copilot-swe-agent',
              followers_url: 'https://api.github.com/users/Copilot/followers',
              following_url: 'https://api.github.com/users/Copilot/following{/other_user}',
              gists_url: 'https://api.github.com/users/Copilot/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/Copilot/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/Copilot/subscriptions',
              organizations_url: 'https://api.github.com/users/Copilot/orgs',
              repos_url: 'https://api.github.com/users/Copilot/repos',
              events_url: 'https://api.github.com/users/Copilot/events{/privacy}',
              received_events_url: 'https://api.github.com/users/Copilot/received_events',
              type: 'Bot',
              user_view_type: 'public',
              site_admin: false
            }
          ],
          milestone: {
            url: 'https://api.github.com/repos/mattleibow/triage-assistant/milestones/1',
            html_url: 'https://github.com/mattleibow/triage-assistant/milestone/1',
            labels_url: 'https://api.github.com/repos/mattleibow/triage-assistant/milestones/1/labels',
            id: 13352621,
            node_id: 'MI_kwDOOy552s4Ay76t',
            number: 1,
            title: 'v1',
            description: null,
            creator: {
              login: 'mattleibow',
              id: 1096616,
              node_id: 'MDQ6VXNlcjEwOTY2MTY=',
              avatar_url: 'https://avatars.githubusercontent.com/u/1096616?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/mattleibow',
              html_url: 'https://github.com/mattleibow',
              followers_url: 'https://api.github.com/users/mattleibow/followers',
              following_url: 'https://api.github.com/users/mattleibow/following{/other_user}',
              gists_url: 'https://api.github.com/users/mattleibow/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/mattleibow/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/mattleibow/subscriptions',
              organizations_url: 'https://api.github.com/users/mattleibow/orgs',
              repos_url: 'https://api.github.com/users/mattleibow/repos',
              events_url: 'https://api.github.com/users/mattleibow/events{/privacy}',
              received_events_url: 'https://api.github.com/users/mattleibow/received_events',
              type: 'User',
              user_view_type: 'public',
              site_admin: false
            },
            open_issues: 2,
            closed_issues: 0,
            state: 'open',
            created_at: '2025-07-26T10:37:16Z',
            updated_at: '2025-07-26T11:14:13Z',
            due_on: null,
            closed_at: null
          },
          comments: 1,
          created_at: '2025-07-26T10:36:49Z',
          updated_at: '2025-07-26T10:38:08Z',
          closed_at: null,
          author_association: 'OWNER',
          active_lock_reason: null,
          sub_issues_summary: {
            total: 0,
            completed: 0,
            percent_completed: 0
          },
          issue_dependencies_summary: {
            blocked_by: 0,
            total_blocked_by: 0,
            blocking: 0,
            total_blocking: 0
          },
          body: '## Description\n\nThis is an issue for the unit tests and not a real one.\n\nWe need some real data to allow for real tests.',
          reactions: {
            url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/32/reactions',
            total_count: 4,
            '+1': 1,
            '-1': 0,
            laugh: 0,
            hooray: 0,
            confused: 0,
            heart: 0,
            rocket: 1,
            eyes: 2
          },
          timeline_url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/32/timeline',
          performed_via_github_app: null,
          state_reason: null,
          score: 1
        },
        {
          url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/31',
          repository_url: 'https://api.github.com/repos/mattleibow/triage-assistant',
          labels_url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/31/labels{/name}',
          comments_url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/31/comments',
          events_url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/31/events',
          html_url: 'https://github.com/mattleibow/triage-assistant/issues/31',
          id: 3263967334,
          node_id: 'I_kwDOOy552s7CjDBm',
          number: 31,
          title: 'Test Issue',
          user: {
            login: 'mattleibow',
            id: 1096616,
            node_id: 'MDQ6VXNlcjEwOTY2MTY=',
            avatar_url: 'https://avatars.githubusercontent.com/u/1096616?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/mattleibow',
            html_url: 'https://github.com/mattleibow',
            followers_url: 'https://api.github.com/users/mattleibow/followers',
            following_url: 'https://api.github.com/users/mattleibow/following{/other_user}',
            gists_url: 'https://api.github.com/users/mattleibow/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/mattleibow/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/mattleibow/subscriptions',
            organizations_url: 'https://api.github.com/users/mattleibow/orgs',
            repos_url: 'https://api.github.com/users/mattleibow/repos',
            events_url: 'https://api.github.com/users/mattleibow/events{/privacy}',
            received_events_url: 'https://api.github.com/users/mattleibow/received_events',
            type: 'User',
            user_view_type: 'public',
            site_admin: false
          },
          labels: [],
          state: 'closed',
          locked: false,
          assignee: null,
          assignees: [],
          milestone: null,
          comments: 1,
          created_at: '2025-07-25T17:53:45Z',
          updated_at: '2025-07-26T10:33:19Z',
          closed_at: '2025-07-26T10:33:19Z',
          author_association: 'OWNER',
          active_lock_reason: null,
          sub_issues_summary: {
            total: 0,
            completed: 0,
            percent_completed: 0
          },
          issue_dependencies_summary: {
            blocked_by: 0,
            total_blocked_by: 0,
            blocking: 0,
            total_blocking: 0
          },
          body: 'Test',
          reactions: {
            url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/31/reactions',
            total_count: 1,
            '+1': 1,
            '-1': 0,
            laugh: 0,
            hooray: 0,
            confused: 0,
            heart: 0,
            rocket: 0,
            eyes: 0
          },
          timeline_url: 'https://api.github.com/repos/mattleibow/triage-assistant/issues/31/timeline',
          performed_via_github_app: null,
          state_reason: 'completed',
          score: 1
        }
      ]
    }
  }
}
