name: 'Triage Issues and Pull Requests'

on:
  # When someone opens a new issue
  issues:
    types: [opened]
  # When someone opens a new pull request
  pull_request:
    types: [opened]
  # When someone adds the "/triage" comments
  issue_comment:
    types: [created]
  # When the workflow is run manually
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to triage'
        required: false
        type: number
        default: ''
      issue_query:
        description: 'GitHub search query to find issues to triage (e.g., "is:issue state:open created:>@today-30d")'
        required: false
        type: string
        default: ''
      dry_run:
        description: 'Dry Run (no writes)'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  issues: write
  pull-requests: write
  models: read

jobs:
  triage:
    name: Triage
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issues' ||
      github.event_name == 'pull_request' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/triage'))
    env:
      TRIAGE_AI_MODEL: openai/gpt-4o-mini # slightly cheaper model
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get Issue or PR Number
        id: get-number
        shell: pwsh
        run: |
          if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            $number="${{ inputs.issue_number }}"
          } else {
            $number="${{ github.event.number }}"
          }
          echo "number=$number" >> $env:GITHUB_OUTPUT
          echo "I will triage issue number #$number"

      - name: Apply Labels and Comment
        uses: ./apply-labels/
        with:
          issue: ${{ steps.get-number.outputs.number || '' }}
          issue-query: ${{ inputs.issue_query || '' }}
          apply-labels: true
          apply-comment: true
          dry-run: ${{ inputs.dry_run || false }}
